"use client";

import { useState } from "react";
import Image from "next/image";
import { PortalShell } from "@/components/portal-shell";
import { Icon } from "@/components/icon";
import { projects } from "@/lib/data";
import { Pill, ProgressBar } from "@/components/ui";

export default function ComparadorPage() {
  const [selected, setSelected] = useState(projects.map((p) => p.id));
  const visible = projects.filter((p) => selected.includes(p.id));
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((x) => x !== id) : current.length < 3 ? [...current, id] : current);
  return <PortalShell role="asesor" title="Comparador de proyectos" subtitle="Contrasta alternativas con base en el perfil activo de Daniela Rojas." actions={<button className="inline-flex h-11 items-center gap-2 rounded-full bg-[#0c1620] px-5 text-xs font-semibold text-white"><Icon name="mail" className="h-4 w-4" />Enviar comparación</button>}><div className="surface-card p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="text-xs font-semibold">Proyectos seleccionados</div><p className="mt-1 text-[10px] text-black/40">Selecciona hasta 3 alternativas.</p></div><div className="flex flex-wrap gap-2">{projects.map((p) => <button key={p.id} onClick={() => toggle(p.id)} className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-xs font-semibold ${selected.includes(p.id) ? "border-[#0067b1] bg-[#0067b1] text-white" : "border-black/10 bg-white text-black/45"}`}>{selected.includes(p.id) ? <Icon name="check" className="h-3.5 w-3.5" /> : <Icon name="plus" className="h-3.5 w-3.5" />}{p.name}</button>)}</div></div></div><div className="mt-5 overflow-x-auto"><div className="grid min-w-[900px] gap-4" style={{ gridTemplateColumns: `190px repeat(${Math.max(visible.length,1)}, minmax(220px, 1fr))` }}><div /><>{visible.map((p) => <div key={p.id} className="surface-card overflow-hidden"><div className="relative h-36"><Image src={p.image} alt={p.name} fill className="object-cover" /><div className="absolute left-3 top-3"><Pill tone="green">{p.compatibility}% match</Pill></div></div><div className="p-5"><div className="text-xs text-[#0067b1]">{p.city} · {p.zone}</div><h2 className="mt-1 text-lg font-semibold">{p.name}</h2></div></div>)}</><div className="rounded-[18px] bg-black/[.03] p-4 text-xs font-semibold">Compatibilidad</div>{visible.map((p) => <div key={`${p.id}-match`} className="rounded-[18px] bg-white p-4"><div className="text-xl font-semibold">{p.compatibility}%</div><div className="mt-3"><ProgressBar value={p.compatibility} /></div></div>)}{[
          ["Precio desde", (p:typeof projects[number])=>p.priceLabel], ["Área",(p:typeof projects[number])=>p.area], ["Habitaciones",(p:typeof projects[number])=>p.rooms], ["Entrega",(p:typeof projects[number])=>p.delivery], ["Cuota inicial estimada",(p:typeof projects[number])=>p.id === "reserva-del-parque" ? "$29,8 M" : p.id === "senderos-de-la-sabana" ? "$26,2 M" : "$23,7 M"], ["Cuota mensual estimada",(p:typeof projects[number])=>p.id === "reserva-del-parque" ? "$1,31 M" : p.id === "senderos-de-la-sabana" ? "$1,18 M" : "$1,04 M"], ["Disponibilidad",(p:typeof projects[number])=>`${p.units} unidades`],
        ].map(([label,getter]) => <div key={label as string} className="contents"><div className="rounded-[18px] bg-black/[.03] p-4 text-xs font-semibold">{label as string}</div>{visible.map((p) => <div key={`${p.id}-${label}`} className="rounded-[18px] bg-white p-4 text-sm font-semibold">{(getter as (p:typeof projects[number])=>string)(p)}</div>)}</div>)}<div className="rounded-[18px] bg-black/[.03] p-4 text-xs font-semibold">Fortalezas</div>{visible.map((p) => <div key={`${p.id}-features`} className="rounded-[18px] bg-white p-4"><ul className="space-y-2 text-xs leading-5 text-black/55">{p.features.slice(0,3).map((f) => <li key={f} className="flex gap-2"><Icon name="check" className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-600" />{f}</li>)}</ul></div>)}</div></div>{visible.length === 0 ? <div className="surface-card mt-5 p-10 text-center text-sm text-black/45">Selecciona al menos un proyecto para comparar.</div> : null}</PortalShell>;
}
