import Link from "next/link";
import { PublicFlowShell } from "@/components/public-flow-shell";
import { Icon } from "@/components/icon";
import { Pill, ProgressBar } from "@/components/ui";

export default function ResultadoPage(){return <PublicFlowShell step={5} eyebrow="Ruta personalizada" title="Estás listo para hablar con un asesor de cierre." description="El motor encontró una combinación favorable de afiliación, capacidad, intención y proyectos compatibles.">
<div className="space-y-5">
<section className="flow-panel overflow-hidden"><div className="grid lg:grid-cols-[minmax(0,1fr)_330px]"><div className="p-7 sm:p-9"><div className="flex flex-col gap-7 sm:flex-row sm:items-center"><div className="relative grid h-36 w-36 shrink-0 place-items-center rounded-full bg-[conic-gradient(#0067b1_0_92%,rgba(0,103,177,.10)_92%_100%)] p-3"><div className="grid h-full w-full place-items-center rounded-full bg-white text-center"><div><div className="text-4xl font-extrabold text-[#0067b1]">92</div><div className="text-[9px] font-bold uppercase tracking-[.1em] text-black/38">Score de cierre</div></div></div></div><div><Pill tone="green">Ruta directa al asesor</Pill><h2 className="mt-4 text-3xl font-bold tracking-[-.045em]">Tu conversación ya no empieza desde cero.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-black/48">El asesor recibirá un resumen de tu afiliación, capacidad estimada, subsidios potenciales, horizonte y proyectos recomendados. Su objetivo será validar y agendar visita.</p></div></div></div><aside className="border-t border-black/[.06] bg-[#111820] p-7 text-white lg:border-l lg:border-t-0"><div className="text-[9px] font-bold uppercase tracking-[.14em] text-[#ffd000]">Decisión del motor</div><div className="mt-5 space-y-4">{[["Afiliación","Afiliado validable"],["Capacidad estimada","$175M–$210M"],["Subsidio","Potencialmente aplicable"],["Horizonte","0–3 meses"],["Acción","Contacto en menos de 15 min"]].map(([l,v])=><div key={l} className="border-b border-white/10 pb-3"><div className="text-[9px] text-white/35">{l}</div><div className="mt-1 text-xs font-bold">{v}</div></div>)}</div></aside></div></section>
<div className="grid gap-5 lg:grid-cols-3"><section className="surface-card p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-[#0067b1]/8 text-[#0067b1]"><Icon name="money" className="h-5 w-5" /></span><h3 className="text-sm font-bold">Capacidad orientativa</h3></div><div className="mt-5 text-3xl font-extrabold text-[#0067b1]">$175M–$210M</div><p className="mt-2 text-[10px] leading-5 text-black/43">No constituye aprobación de crédito.</p></section><section className="surface-card p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-[#ffd000]/22"><Icon name="home" className="h-5 w-5" /></span><h3 className="text-sm font-bold">Mejor proyecto</h3></div><div className="mt-5 text-2xl font-extrabold">Reserva del Parque</div><div className="mt-5"><ProgressBar value={94} label="Compatibilidad" /></div></section><section className="surface-card p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-emerald-50 text-emerald-700"><Icon name="target" className="h-5 w-5" /></span><h3 className="text-sm font-bold">Siguiente paso</h3></div><div className="mt-5 text-2xl font-extrabold">Agendar visita</div><p className="mt-2 text-[10px] leading-5 text-black/43">El asesor valida disponibilidad y condiciones finales.</p></section></div>
<section className="surface-card p-6 sm:p-8"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Resumen que recibe el asesor</h3><p className="mt-1 text-[10px] text-black/40">Información útil para cerrar, no para volver a explorar.</p></div><Icon name="briefcase" className="h-5 w-5 text-[#0067b1]" /></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Fortalezas","Ingreso estable, ahorro inicial y afiliación."],["Por validar","Saldo de cesantías y obligaciones exactas."],["Preferencia","Bogotá, 2–3 habitaciones."],["Proyectos","3 opciones priorizadas, no catálogo completo."]].map(([t,d])=><div key={t} className="rounded-[18px] bg-black/[.025] p-5"><div className="text-xs font-bold">{t}</div><p className="mt-2 text-[10px] leading-5 text-black/48">{d}</p></div>)}</div></section>
<div className="flex flex-col gap-3 sm:flex-row"><Link href="/vivienda/agendar" className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-full bg-[#0067b1] px-6 text-sm font-bold text-white">Agendar visita con asesor <Icon name="calendar" className="h-4 w-4" /></Link><Link href="/vivienda/proyectos" className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-black/[.08] bg-white px-6 text-sm font-bold">Ver mis 3 proyectos <Icon name="building" className="h-4 w-4" /></Link></div>
<p className="rounded-[16px] border border-black/[.065] bg-white/75 p-4 text-[10px] leading-5 text-black/40">La plataforma no aprueba créditos, no consulta DataCrédito y no garantiza subsidios. Realiza perfilamiento, priorización, recomendación y preparación comercial.</p>
</div></PublicFlowShell>}
