/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Session */
        post: operations["sync_session_api_v1_leads_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Handoff */
        post: operations["request_handoff_api_v1_leads__lead_id__handoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update Handoff Status */
        patch: operations["update_handoff_status_api_v1_leads__lead_id__handoff_patch"];
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Lead */
        post: operations["claim_lead_api_v1_leads__lead_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Lead */
        post: operations["assign_lead_api_v1_leads__lead_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Commercial Workflow */
        patch: operations["update_commercial_workflow_api_v1_leads__lead_id__workflow_patch"];
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lead Activities */
        get: operations["list_lead_activities_api_v1_leads__lead_id__activities_get"];
        put?: never;
        /** Create Lead Activity */
        post: operations["create_lead_activity_api_v1_leads__lead_id__activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/nurture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Nurture */
        put: operations["update_nurture_api_v1_leads__lead_id__nurture_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_api_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Conversation */
        post: operations["start_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_conversations__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_v1_conversations__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{session_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline Conversation */
        post: operations["decline_conversation_api_v1_conversations__session_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/chat-records/{record_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Chat Record */
        post: operations["review_chat_record_api_v1_conversations_chat_records__record_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/chat-training/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat Training Summary */
        get: operations["chat_training_summary_api_v1_conversations_chat_training_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/chat-training/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Chat Training */
        post: operations["export_chat_training_api_v1_conversations_chat_training_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend_api_v1_projects_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_v1_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Quality */
        get: operations["data_quality_api_v1_analytics_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Info */
        get: operations["model_info_api_v1_analytics_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/advisor-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Advisor Dashboard */
        get: operations["advisor_dashboard_api_v1_analytics_advisor_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_api_v1_ai_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/advisor-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advisor Summary */
        post: operations["advisor_summary_api_v1_ai_advisor_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Quality */
        get: operations["data_quality_api_v1_admin_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Registry */
        get: operations["model_registry_api_v1_admin_model_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scope */
        get: operations["scope_api_v1_admin_scope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquisitionPayload */
        AcquisitionPayload: {
            /**
             * Source
             * @default web
             */
            source: string;
            /**
             * Campaign
             * @default direct
             */
            campaign: string;
            /**
             * Content
             * @default unknown
             */
            content: string;
            /** Lead Reference */
            lead_reference?: string | null;
            /** Is Paid */
            is_paid?: boolean | null;
        };
        /** ActivityCreateRequest */
        ActivityCreateRequest: {
            activity_type: components["schemas"]["CommercialActivityType"];
            channel: components["schemas"]["ContactChannel"];
            /** Result */
            result: string;
            /**
             * Managed At
             * Format: date-time
             */
            managed_at: string;
            /** Next Follow Up At */
            next_follow_up_at?: string | null;
            /** Note */
            note?: string | null;
            /** Expected Workflow Version */
            expected_workflow_version: number;
        };
        /** ActivityOperationResponse */
        ActivityOperationResponse: {
            activity: components["schemas"]["ActivityResponse"];
            workflow: components["schemas"]["CommercialWorkflowResponse"];
        };
        /** ActivityResponse */
        ActivityResponse: {
            /** Id */
            id: string;
            /** Lead Id */
            lead_id: string;
            /** Advisor Id */
            advisor_id: string;
            activity_type: components["schemas"]["CommercialActivityType"];
            channel: components["schemas"]["ContactChannel"];
            /** Result */
            result: string;
            /** Managed At */
            managed_at: string | null;
            /** Next Follow Up At */
            next_follow_up_at?: string | null;
            /** Note */
            note?: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** AdvisorDashboardResponse */
        AdvisorDashboardResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            live: components["schemas"]["AdvisorLiveSnapshot"];
            historical: components["schemas"]["HistoricalSnapshot"];
            model: components["schemas"]["ModelSnapshot"];
            /** Insights */
            insights?: components["schemas"]["AdvisorInsight"][];
            /** Assets */
            assets?: components["schemas"]["DataAsset"][];
            /** Warnings */
            warnings?: string[];
        };
        /** AdvisorHandoffPatch */
        AdvisorHandoffPatch: {
            status: components["schemas"]["HandoffStatus"];
            /** Next Action */
            next_action?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AdvisorInsight */
        AdvisorInsight: {
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /**
             * Tone
             * @default INFO
             * @enum {string}
             */
            tone: "INFO" | "SUCCESS" | "ATTENTION";
        };
        /** AdvisorLiveSnapshot */
        AdvisorLiveSnapshot: {
            /** Total Leads */
            total_leads: number;
            /** Ready For Advisor */
            ready_for_advisor: number;
            /** Accompaniment */
            accompaniment: number;
            /** Needs Validation */
            needs_validation: number;
            /** Pending Handoffs */
            pending_handoffs: number;
            /** Paid Leads */
            paid_leads: number;
            /** Affiliation Identified */
            affiliation_identified: number;
            /** Route Distribution */
            route_distribution?: components["schemas"]["DistributionItem"][];
        };
        /** AdvisorSummary */
        AdvisorSummary: {
            /** Headline */
            headline: string;
            /** Profile Summary */
            profile_summary: string;
            /** Closing Focus */
            closing_focus: string;
            /** Pending Validations */
            pending_validations: string[];
            /** Risk Notes */
            risk_notes: string[];
        };
        /**
         * AgentMode
         * @enum {string}
         */
        AgentMode: "OPENAI_AGENTS" | "DETERMINISTIC_FALLBACK";
        /** AgentUsage */
        AgentUsage: {
            /**
             * Requests
             * @default 0
             */
            requests: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /** AssignLeadRequest */
        AssignLeadRequest: {
            /** Advisor Id */
            advisor_id: string;
            /** Expected Workflow Version */
            expected_workflow_version: number;
            /** Reason */
            reason: string;
            /**
             * Assigned At
             * Format: date-time
             */
            assigned_at: string;
        };
        /** CapacityAssessment */
        CapacityAssessment: {
            /**
             * Monthly Income Estimate
             * @default 0
             */
            monthly_income_estimate: number;
            /**
             * Commitment Ratio
             * @default 0
             */
            commitment_ratio: number;
            /**
             * Maximum Housing Ratio
             * @default 0
             */
            maximum_housing_ratio: number;
            /**
             * Estimated Housing Payment
             * @default 0
             */
            estimated_housing_payment: number;
            /**
             * Status
             * @default UNKNOWN
             */
            status: string;
        };
        /** CapacityResult */
        CapacityResult: {
            /** Estimated Amount */
            estimated_amount?: number | null;
            /** Estimated Monthly Payment */
            estimated_monthly_payment?: number | null;
            /**
             * Disclaimer
             * @default Estimación orientativa; no constituye aprobación crediticia.
             */
            disclaimer: string;
        };
        /** ChatLeadFeedbackRequest */
        ChatLeadFeedbackRequest: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "POSITIVE" | "NEGATIVE" | "NEUTRAL";
            /** Corrected Next Action */
            corrected_next_action?: string | null;
            /** Corrected Route */
            corrected_route?: string | null;
            /**
             * Outcome
             * @default UNKNOWN
             * @enum {string}
             */
            outcome: "UNKNOWN" | "CONTACTED" | "APPOINTMENT_SCHEDULED" | "CLOSED_WON" | "CLOSED_LOST" | "NURTURE_PROGRESS" | "OPTED_OUT";
            /** Note */
            note?: string | null;
            /**
             * Training Eligible
             * @default true
             */
            training_eligible: boolean;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
        };
        /** ChatLeadRecord */
        ChatLeadRecord: {
            /** Id */
            id: string;
            /** External Turn Id */
            external_turn_id: string;
            /** User Message */
            user_message: string;
            /** Assistant Message */
            assistant_message: string;
            /** Conversation State */
            conversation_state: string;
            /** Next Action */
            next_action: string;
            /** Route */
            route: string;
            /** Agent Mode */
            agent_mode: string;
            /** Model Name */
            model_name: string;
            /** Prompt Version */
            prompt_version: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Training Eligible */
            training_eligible: boolean;
            /** Feedback Rating */
            feedback_rating?: string | null;
            /** Corrected Next Action */
            corrected_next_action?: string | null;
            /** Corrected Route */
            corrected_route?: string | null;
            /** Observed Outcome */
            observed_outcome?: string | null;
            /** Reviewer Note */
            reviewer_note?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatLeadTrainingSummary */
        ChatLeadTrainingSummary: {
            /** Total Records */
            total_records: number;
            /** Eligible Records */
            eligible_records: number;
            /** Positive Records */
            positive_records: number;
            /** Negative Records */
            negative_records: number;
            /** Labeled Outcomes */
            labeled_outcomes: number;
            /** Exported Path */
            exported_path?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * CommercialActivityType
         * @enum {string}
         */
        CommercialActivityType: "NOTE" | "CONTACT_ATTEMPT" | "CONTACT_SUCCESS" | "FOLLOW_UP_SCHEDULED" | "APPOINTMENT_SCHEDULED" | "CLOSED_WON" | "CLOSED_LOST" | "OPTED_OUT";
        /**
         * CommercialState
         * @enum {string}
         */
        CommercialState: "PENDING" | "ASSIGNED" | "IN_PROGRESS" | "FOLLOW_UP" | "APPOINTMENT_SCHEDULED" | "CLOSED_WON" | "CLOSED_LOST" | "OPTED_OUT";
        /** CommercialWorkflowResponse */
        CommercialWorkflowResponse: {
            /** Lead Id */
            lead_id: string;
            state: components["schemas"]["CommercialState"];
            /** Workflow Version */
            workflow_version: number;
            /** Assigned Advisor Id */
            assigned_advisor_id?: string | null;
            /** Next Action */
            next_action: string;
            /** Next Follow Up At */
            next_follow_up_at?: string | null;
            /** Sla Due At */
            sla_due_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * ContactChannel
         * @enum {string}
         */
        ContactChannel: "PHONE" | "WHATSAPP" | "EMAIL" | "IN_PERSON";
        /** ConversationMessageRequest */
        ConversationMessageRequest: {
            /** External Turn Id */
            external_turn_id: string;
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Lead Id */
            lead_id: string;
            /** Session Id */
            session_id: string;
            /** External Turn Id */
            external_turn_id?: string | null;
            /** Assistant Message */
            assistant_message: string;
            conversation_state: components["schemas"]["ConversationState"];
            /** Next Action */
            next_action: string;
            /** Quick Replies */
            quick_replies?: string[];
            /** Extracted Fields */
            extracted_fields?: string[];
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /** Discovery */
            discovery?: {
                [key: string]: unknown;
            };
            journey: components["schemas"]["SessionSyncResponse"];
            /**
             * Readiness Score
             * @default 0
             */
            readiness_score: number;
            /**
             * Confidence Score
             * @default 0
             */
            confidence_score: number;
            /**
             * Priority
             * @default LOW
             */
            priority: string;
            agent_mode: components["schemas"]["AgentMode"];
            agent_usage?: components["schemas"]["AgentUsage"];
            regulatory: components["schemas"]["RegulatoryResult"];
            /** Continue Conversation */
            continue_conversation: boolean;
            /** Completed */
            completed: boolean;
            /** Training Record Id */
            training_record_id?: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Model Name */
            model_name: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Prospect Access Token */
            prospect_access_token?: string | null;
        };
        /**
         * ConversationState
         * @enum {string}
         */
        ConversationState: "CONSENT" | "DISCOVERY" | "AFFILIATION" | "FINANCIAL_DISCOVERY" | "BENEFITS_DISCOVERY" | "PROJECT_MATCHING" | "NURTURE_COACHING" | "REGULATORY_REVIEW" | "CONTACT_CAPTURE" | "READY_FOR_ADVISOR" | "COMPLETED" | "OPTED_OUT";
        /** ConversationTurnPayload */
        ConversationTurnPayload: {
            /** Id */
            id: string;
            /** User Text */
            user_text: string;
            /** Assistant Text */
            assistant_text: string;
            /** Extracted Fields */
            extracted_fields?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DataAsset */
        DataAsset: {
            /** Name */
            name: string;
            /**
             * Area
             * @enum {string}
             */
            area: "processed" | "report" | "artifact";
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "AVAILABLE" | "MISSING";
            /** Rows */
            rows?: number | null;
            /** Updated At */
            updated_at?: string | null;
            /** Description */
            description: string;
        };
        /** DeclineConversationRequest */
        DeclineConversationRequest: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DiscoveryPayload */
        "DiscoveryPayload-Input": {
            /** Housing Vision */
            housing_vision?: string | null;
            /** Intended For */
            intended_for?: string | null;
            /** Motivation */
            motivation?: string | null;
            /** Obstacle */
            obstacle?: string | null;
            /** Advance Need */
            advance_need?: string | null;
        };
        /** DiscoveryPayload */
        "DiscoveryPayload-Output": {
            /** Housingvision */
            housingVision?: string | null;
            /** Intendedfor */
            intendedFor?: string | null;
            /** Motivation */
            motivation?: string | null;
            /** Obstacle */
            obstacle?: string | null;
            /** Advanceneed */
            advanceNeed?: string | null;
        };
        /** DistributionItem */
        DistributionItem: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Share */
            share: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** ExtractRequest */
        ExtractRequest: {
            /** Message */
            message: string;
        };
        /** ExtractedSignals */
        ExtractedSignals: {
            /** Affiliation */
            affiliation?: string | null;
            /** Location */
            location?: string | null;
            /** Horizon */
            horizon?: string | null;
            /** Income Range */
            income_range?: string | null;
            /** Obligations */
            obligations?: string | null;
            /** Savings */
            savings?: string | null;
            /**
             * Requests Advisor
             * @default false
             */
            requests_advisor: boolean;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Requires Confirmation
             * @default true
             */
            requires_confirmation: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffResult */
        HandoffResult: {
            /**
             * Requested
             * @default false
             */
            requested: boolean;
            /** @default NOT_REQUESTED */
            status: components["schemas"]["HandoffStatus"];
            /** Channel */
            channel?: string | null;
            /** Time Preference */
            time_preference?: string | null;
            /** Requested At */
            requested_at?: string | null;
            /** Project Ids */
            project_ids?: string[];
            /** Next Action */
            next_action: string;
        };
        /**
         * HandoffStatus
         * @enum {string}
         */
        HandoffStatus: "NOT_REQUESTED" | "REQUESTED" | "IN_REVIEW" | "ASSIGNED" | "CONTACTED" | "CLOSED";
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
            /** Model Available */
            model_available: boolean;
            /** Processed Data Available */
            processed_data_available: boolean;
        };
        /** HistoricalSnapshot */
        HistoricalSnapshot: {
            /** Pipeline Generated At */
            pipeline_generated_at?: string | null;
            /** Status */
            status: string;
            /** Historical Records */
            historical_records: number;
            /** Model Records */
            model_records: number;
            /** Mapped Records */
            mapped_records: number;
            /** Mapped Projects */
            mapped_projects: number;
            /** Withdrawals */
            withdrawals: number;
            /** Withdrawal Rate */
            withdrawal_rate: number;
            /** Affiliate Share */
            affiliate_share: number;
            /** Non Affiliate Share */
            non_affiliate_share: number;
            /** Quality Issue Rows */
            quality_issue_rows: number;
            /** Top Projects */
            top_projects?: components["schemas"]["DistributionItem"][];
            /** Top Channels */
            top_channels?: components["schemas"]["DistributionItem"][];
        };
        /** InternalEvaluationDetail */
        InternalEvaluationDetail: {
            route: components["schemas"]["LeadRoute"];
            priority: components["schemas"]["Priority"];
            /**
             * Readiness Score
             * @default 0
             */
            readiness_score: number;
            /**
             * Confidence Score
             * @default 0
             */
            confidence_score: number;
            /** Reason Codes */
            reason_codes?: string[];
            /** Blockers */
            blockers?: string[];
            capacity: components["schemas"]["CapacityAssessment"];
            /** Recommendations */
            recommendations?: components["schemas"]["InternalProjectRecommendation"][];
            /** Rule Version */
            rule_version: string;
            /** Model Version */
            model_version: string;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /** InternalProjectRecommendation */
        InternalProjectRecommendation: {
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** Reasons */
            reasons?: string[];
            /** Brochure Url */
            brochure_url?: string | null;
            /** Tour Urls */
            tour_urls?: string[];
            /** Model Source */
            model_source: string;
        };
        /** LeadAuditEvent */
        LeadAuditEvent: {
            /** Event Type */
            event_type: string;
            /** Actor */
            actor: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LeadDetailResponse */
        LeadDetailResponse: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** First Name */
            first_name: string | null;
            /** Source */
            source: string;
            /** Campaign */
            campaign: string;
            /** Content */
            content: string;
            /** Is Paid */
            is_paid: boolean | null;
            /** Status */
            status: string;
            /** Consent Accepted At */
            consent_accepted_at: string | null;
            profile: components["schemas"]["ProfilePayload-Output"];
            discovery: components["schemas"]["DiscoveryPayload-Output"];
            /** Turns */
            turns: components["schemas"]["LeadDetailTurn"][];
            evaluation: components["schemas"]["InternalEvaluationDetail"] | null;
            journey?: components["schemas"]["SessionSyncResponse"] | null;
            commercial_workflow?: components["schemas"]["CommercialWorkflowResponse"] | null;
            /** Enrichments */
            enrichments: components["schemas"]["LeadEnrichmentDetail"][];
            /** Audit Events */
            audit_events: components["schemas"]["LeadAuditEvent"][];
            /** Chat Records */
            chat_records?: components["schemas"]["ChatLeadRecord"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LeadDetailTurn */
        LeadDetailTurn: {
            /** Id */
            id: string;
            /** User Text */
            user_text: string;
            /** Assistant Text */
            assistant_text: string;
            /** Extracted Fields */
            extracted_fields?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LeadEnrichmentDetail */
        LeadEnrichmentDetail: {
            /** Provider */
            provider: string;
            /** Source Url */
            source_url?: string | null;
            /** Purpose */
            purpose: string;
            /** Status */
            status: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LeadListItem */
        LeadListItem: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** First Name */
            first_name: string | null;
            /** Source */
            source: string;
            /** Campaign */
            campaign: string;
            /** Is Paid */
            is_paid: boolean | null;
            /** Status */
            status: string;
            /** Affiliation Status */
            affiliation_status: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /** Route */
            route: string | null;
            /** Priority */
            priority: string | null;
            readiness_level: components["schemas"]["ReadinessLevel"] | null;
            /** Readiness Score */
            readiness_score?: number | null;
            /** Confidence Score */
            confidence_score?: number | null;
            /** Readiness Factors */
            readiness_factors?: string[];
            /** Readiness Blockers */
            readiness_blockers?: string[];
            /** Estimated Amount */
            estimated_amount?: number | null;
            /** Estimated Monthly Payment */
            estimated_monthly_payment?: number | null;
            /** Top Project Id */
            top_project_id: string | null;
            /** Conversation State */
            conversation_state?: string | null;
            /** Agent Mode */
            agent_mode?: string | null;
            /** Regulatory Status */
            regulatory_status?: string | null;
            /** Nurture Primary Gap */
            nurture_primary_gap?: string | null;
            /** Nurture Status */
            nurture_status?: string | null;
            /** Nurture Target Amount */
            nurture_target_amount?: number | null;
            /**
             * Nurture Intervention Required
             * @default false
             */
            nurture_intervention_required: boolean;
            /** Nurture Milestones */
            nurture_milestones?: components["schemas"]["NurtureMilestone"][];
            /**
             * Handoff Requested
             * @default false
             */
            handoff_requested: boolean;
            /** Handoff Status */
            handoff_status?: string | null;
            /** Assigned Advisor Id */
            assigned_advisor_id?: string | null;
            commercial_state?: components["schemas"]["CommercialState"] | null;
            /** Workflow Version */
            workflow_version?: number | null;
            /** Next Follow Up At */
            next_follow_up_at?: string | null;
            /** Sla Due At */
            sla_due_at?: string | null;
            /**
             * Sla Overdue
             * @default false
             */
            sla_overdue: boolean;
            /** Next Action */
            next_action?: string | null;
            /** Review Date */
            review_date?: string | null;
            /**
             * Qualified At
             * Format: date-time
             */
            qualified_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LeadRoute
         * @enum {string}
         */
        LeadRoute: "READY_TO_CLOSE" | "NEEDS_VALIDATION" | "NON_AFFILIATE_REVIEW" | "REGULATORY_WAITLIST" | "NURTURE" | "FINANCIAL_PREPARATION" | "OPTED_OUT";
        /** LivenessResponse */
        LivenessResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ModelSnapshot */
        ModelSnapshot: {
            /** Version */
            version: string;
            /** Available */
            available: boolean;
            /** Source Dataset */
            source_dataset?: string | null;
            /** Train Rows */
            train_rows: number;
            /** Test Rows */
            test_rows: number;
            /** Top1 Accuracy */
            top1_accuracy: number;
            /** Recall At 3 */
            recall_at_3: number;
            /** Popularity Recall At 3 */
            popularity_recall_at_3: number;
            /** Recall Uplift Percentage Points */
            recall_uplift_percentage_points: number;
            /** Coverage Top1 */
            coverage_top1: number;
            /** Trained At */
            trained_at?: string | null;
            /** Claim */
            claim: string;
        };
        /**
         * NurtureJourneyStatus
         * @enum {string}
         */
        NurtureJourneyStatus: "ACTIVE" | "PAUSED" | "REEVALUATION_PENDING" | "NEEDS_ATTENTION";
        /** NurtureMilestone */
        NurtureMilestone: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** Completed At */
            completed_at?: string | null;
        };
        /** NurturePlan */
        NurturePlan: {
            /** Primary Gap */
            primary_gap?: string | null;
            /** Target Amount */
            target_amount?: number | null;
            /** Review Date */
            review_date?: string | null;
            /** @default ACTIVE */
            status: components["schemas"]["NurtureJourneyStatus"];
            /**
             * Intervention Required
             * @default false
             */
            intervention_required: boolean;
            /** Milestones */
            milestones?: components["schemas"]["NurtureMilestone"][];
        };
        /** NurtureProgressRequest */
        NurtureProgressRequest: {
            status: components["schemas"]["NurtureJourneyStatus"];
            /** Completed Milestone Ids */
            completed_milestone_ids?: string[];
            /**
             * Intervention Required
             * @default false
             */
            intervention_required: boolean;
            /** Requested Reevaluation At */
            requested_reevaluation_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "HIGH" | "MEDIUM" | "LOW";
        /** ProfilePayload */
        "ProfilePayload-Input": {
            /** Affiliation */
            affiliation?: string | null;
            /** Location */
            location?: string | null;
            /** Horizon */
            horizon?: string | null;
            /** Income Range */
            income_range?: string | null;
            /** Obligations */
            obligations?: string | null;
            /** Savings */
            savings?: string | null;
            /** Household Size */
            household_size?: string | null;
            /** Subsidy Interest */
            subsidy_interest?: string | null;
            /** Housing Goal */
            housing_goal?: string | null;
            /** Home Ownership */
            home_ownership?: string | null;
            /** Credit Status */
            credit_status?: string | null;
            /** Visit Intent */
            visit_intent?: string | null;
            /** Monthly Savings Goal */
            monthly_savings_goal?: string | null;
            /** Debt Reduction Plan */
            debt_reduction_plan?: string | null;
            /** Follow Up Preference */
            follow_up_preference?: string | null;
            /** Preferred Channel */
            preferred_channel?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Contact Time Preference */
            contact_time_preference?: string | null;
            /** Contact Consent */
            contact_consent?: string | null;
            /** Requests Advisor */
            requests_advisor?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ProfilePayload */
        "ProfilePayload-Output": {
            /** Affiliation */
            affiliation?: string | null;
            /** Location */
            location?: string | null;
            /** Horizon */
            horizon?: string | null;
            /** Incomerange */
            incomeRange?: string | null;
            /** Obligations */
            obligations?: string | null;
            /** Savings */
            savings?: string | null;
            /** Householdsize */
            householdSize?: string | null;
            /** Subsidyinterest */
            subsidyInterest?: string | null;
            /** Housinggoal */
            housingGoal?: string | null;
            /** Homeownership */
            homeOwnership?: string | null;
            /** Creditstatus */
            creditStatus?: string | null;
            /** Visitintent */
            visitIntent?: string | null;
            /** Monthlysavingsgoal */
            monthlySavingsGoal?: string | null;
            /** Debtreductionplan */
            debtReductionPlan?: string | null;
            /** Followuppreference */
            followUpPreference?: string | null;
            /** Preferredchannel */
            preferredChannel?: string | null;
            /** Fullname */
            fullName?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Contacttimepreference */
            contactTimePreference?: string | null;
            /** Contactconsent */
            contactConsent?: string | null;
            /** Requestsadvisor */
            requestsAdvisor?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ProjectRecommendation */
        ProjectRecommendation: {
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Rank */
            rank: number;
            /** Reasons */
            reasons: string[];
            /** Brochure Url */
            brochure_url?: string | null;
            /** Tour Urls */
            tour_urls?: string[];
            /**
             * Purpose
             * @default MATCH
             * @enum {string}
             */
            purpose: "MATCH" | "REFERENCE";
            /** Price From Cop */
            price_from_cop?: number | null;
            /** Price Reference Cop */
            price_reference_cop?: number | null;
            /** Price To Cop */
            price_to_cop?: number | null;
            /** Price Reference Source */
            price_reference_source?: string | null;
            /**
             * Budget Status
             * @default UNKNOWN
             * @enum {string}
             */
            budget_status: "WITHIN_RANGE" | "REFERENCE_ONLY" | "UNKNOWN";
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Development */
            development: string;
            /** Housing Type */
            housing_type?: string | null;
            /** Brochure Url */
            brochure_url?: string | null;
            /** Tour Urls */
            tour_urls?: string[];
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Price From Cop */
            price_from_cop?: number | null;
            /** Price Reference Cop */
            price_reference_cop?: number | null;
            /** Price To Cop */
            price_to_cop?: number | null;
            /** Price Reference Source */
            price_reference_source?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Historical Sample Size
             * @default 0
             */
            historical_sample_size: number;
            /** Historical Profile */
            historical_profile?: {
                [key: string]: unknown;
            };
            /** Source Metadata */
            source_metadata?: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProspectHandoffRequest */
        ProspectHandoffRequest: {
            /** Channel */
            channel: string;
            /** Time Preference */
            time_preference: string;
            /** Project Ids */
            project_ids?: string[];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
        };
        /**
         * ReadinessLevel
         * @enum {string}
         */
        ReadinessLevel: "HIGH" | "DEVELOPING" | "INITIAL";
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
        };
        /** ReadinessResult */
        ReadinessResult: {
            level: components["schemas"]["ReadinessLevel"];
            /** Factors */
            factors?: string[];
            /** Blockers */
            blockers?: string[];
            /** Missing Fields */
            missing_fields?: string[];
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /**
             * Top K
             * @default 3
             */
            top_k: number;
            /** Campaign Project Id */
            campaign_project_id?: string | null;
        };
        /** RegulatoryResult */
        RegulatoryResult: {
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Affiliate Sales */
            affiliate_sales: number;
            /** Non Affiliate Sales */
            non_affiliate_sales: number;
            /** Total Sales */
            total_sales: number;
            /** Non Affiliate Share */
            non_affiliate_share: number;
            /** Non Affiliate Limit */
            non_affiliate_limit: number;
            /** Available Non Affiliate Slots */
            available_non_affiliate_slots: number;
            /** Can Continue */
            can_continue: boolean;
            /** Period */
            period: string;
        };
        /** SessionSyncRequest */
        SessionSyncRequest: {
            /** Session Id */
            session_id: string;
            /**
             * Session Version
             * @default 1
             */
            session_version: number;
            /** Lead Id */
            lead_id?: string | null;
            /** First Name */
            first_name?: string | null;
            acquisition: components["schemas"]["AcquisitionPayload"];
            /** Status */
            status: string;
            /** Consent Accepted At */
            consent_accepted_at?: string | null;
            /**
             * Customer Relationship
             * @default UNKNOWN
             */
            customer_relationship: string;
            profile?: components["schemas"]["ProfilePayload-Input"];
            discovery?: components["schemas"]["DiscoveryPayload-Input"];
            /** Turns */
            turns?: components["schemas"]["ConversationTurnPayload"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionSyncResponse */
        SessionSyncResponse: {
            /** Lead Id */
            lead_id: string;
            /** Session Id */
            session_id: string;
            /** Session Version */
            session_version: number;
            /**
             * Persisted
             * @default true
             */
            persisted: boolean;
            readiness: components["schemas"]["ReadinessResult"];
            route: components["schemas"]["LeadRoute"];
            capacity: components["schemas"]["CapacityResult"];
            nurture_plan?: components["schemas"]["NurturePlan"] | null;
            /** Recommendations */
            recommendations?: components["schemas"]["ProjectRecommendation"][];
            regulatory?: components["schemas"]["RegulatoryResult"] | null;
            handoff: components["schemas"]["HandoffResult"];
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /** Lead Id */
            lead_id?: string | null;
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Changes */
            changes?: {
                [key: string]: unknown;
            };
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Original Route */
            original_route: string;
            /** Simulated Route */
            simulated_route: string;
            /** Original Score */
            original_score: number;
            /** Simulated Score */
            simulated_score: number;
            /** Score Delta */
            score_delta: number;
            /** Changed Fields */
            changed_fields: {
                [key: string]: unknown;
            };
            /** Recommendations */
            recommendations: {
                [key: string]: unknown;
            }[];
            /** Interpretation */
            interpretation: string;
        };
        /** StartConversationRequest */
        StartConversationRequest: {
            /** Session Id */
            session_id: string;
            /** External Lead Id */
            external_lead_id?: string | null;
            /** First Name */
            first_name?: string | null;
            acquisition?: components["schemas"]["AcquisitionPayload"];
            /**
             * Customer Relationship
             * @default UNKNOWN
             */
            customer_relationship: string;
            /**
             * Consent Accepted At
             * Format: date-time
             */
            consent_accepted_at: string;
            known_profile?: components["schemas"]["ProfilePayload-Input"];
            known_discovery?: components["schemas"]["DiscoveryPayload-Input"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SummaryRequest */
        SummaryRequest: {
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowUpdateRequest */
        WorkflowUpdateRequest: {
            state: components["schemas"]["CommercialState"];
            /** Expected Workflow Version */
            expected_workflow_version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Next Follow Up At */
            next_follow_up_at?: string | null;
            /** Outcome */
            outcome?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    sync_session_api_v1_leads_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSyncResponse"];
                };
            };
            /** @description Versión antigua, conflictiva o todavía en proceso. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                limit?: number;
                assigned_to_me?: boolean;
                pending_assignment?: boolean;
                commercial_state?: components["schemas"]["CommercialState"] | null;
                sla_overdue?: boolean;
                overdue_follow_up?: boolean;
                next_action?: string | null;
                reevaluation_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadListItem"][];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario autenticado sin rol de asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_handoff_api_v1_leads__lead_id__handoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProspectHandoffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSyncResponse"];
                };
            };
            /** @description No existe el recorrido solicitado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La ruta actual todavía no permite contacto comercial. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_handoff_status_api_v1_leads__lead_id__handoff_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvisorHandoffPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSyncResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario autenticado sin rol de asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe el recorrido solicitado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_lead_api_v1_leads__lead_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommercialWorkflowResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario autenticado sin rol de asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La oportunidad no está disponible para gestión. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La oportunidad ya tiene un asesor activo. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_lead_api_v1_leads__lead_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignLeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommercialWorkflowResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario autenticado sin rol de asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La oportunidad no tiene flujo comercial. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La versión comercial enviada está desactualizada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_commercial_workflow_api_v1_leads__lead_id__workflow_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommercialWorkflowResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La oportunidad pertenece a otro asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transición inválida o versión desactualizada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lead_activities_api_v1_leads__lead_id__activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"][];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La oportunidad pertenece a otro asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_activity_api_v1_leads__lead_id__activities_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOperationResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La oportunidad pertenece a otro asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflicto de versión o idempotencia. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_nurture_api_v1_leads__lead_id__nurture_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NurtureProgressRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSyncResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario autenticado sin rol de asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe un plan de acompañamiento. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_api_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetailResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario autenticado sin rol de asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe la oportunidad solicitada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_conversations__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_conversation_api_v1_conversations__session_id__decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclineConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_chat_record_api_v1_conversations_chat_records__record_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatLeadFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_training_summary_api_v1_conversations_chat_training_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatLeadTrainingSummary"];
                };
            };
        };
    };
    export_chat_training_api_v1_conversations_chat_training_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatLeadTrainingSummary"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    recommend_api_v1_projects_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_v1_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_analytics_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    data_quality_api_v1_analytics_data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    model_info_api_v1_analytics_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    advisor_dashboard_api_v1_analytics_advisor_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorDashboardResponse"];
                };
            };
            /** @description Bearer Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario autenticado sin rol de asesor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    extract_api_v1_ai_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedSignals"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advisor_summary_api_v1_ai_advisor_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_quality_api_v1_admin_data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    model_registry_api_v1_admin_model_registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    scope_api_v1_admin_scope_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
