"use client";
import { useMemo,useState } from "react";
import { PortalShell } from "@/components/portal-shell";
import { Icon } from "@/components/icon";
import { Pill } from "@/components/ui";

const initial=[
{id:"affiliate",label:"Afiliación y regla 90/10",weight:25,description:"Prioriza afiliados y controla capacidad disponible para no afiliados sin descartarlos."},
{id:"capacity",label:"Capacidad de compra",weight:22,description:"Ingresos, obligaciones y recursos para cuota inicial."},
{id:"intent",label:"Momento de compra",weight:18,description:"Horizonte y señales de intención."},
{id:"subsidy",label:"Subsidio potencial",weight:15,description:"Vivienda actual, ingreso y condiciones generales declaradas."},
{id:"inventory",label:"Afinidad con inventario",weight:12,description:"Precio, ubicación, tamaño y disponibilidad."},
{id:"completeness",label:"Confianza de datos",weight:8,description:"Completitud, consistencia y campos por validar."},
];
export default function ScoringPage(){const [weights,setWeights]=useState(initial);const total=useMemo(()=>weights.reduce((a,b)=>a+b.weight,0),[weights]);return <PortalShell role="admin" title="Motor de decisión y enrutamiento" subtitle="Configura una priorización explicable. El score no aprueba crédito: decide qué preguntar, qué recomendar y cuál debe ser la siguiente acción." actions={<button className="inline-flex h-11 items-center gap-2 rounded-full bg-[#0c1620] px-5 text-xs font-semibold text-white"><Icon name="history" className="h-4 w-4"/>Versiones</button>}>
<div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="surface-card p-6 sm:p-8"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Ponderación de señales</h2><p className="mt-1 text-xs text-black/40">Cada cambio debe conservar explicación, evidencia y rollback.</p></div><Pill tone={total===100?"green":"red"}>Total {total}%</Pill></div><div className="mt-7 space-y-6">{weights.map((w)=><div key={w.id}><div className="flex items-start justify-between gap-4"><div><div className="text-sm font-semibold">{w.label}</div><p className="mt-1 text-xs leading-5 text-black/42">{w.description}</p></div><div className="flex items-center gap-2"><input type="number" min={0} max={50} value={w.weight} onChange={(e)=>setWeights((items)=>items.map((item)=>item.id===w.id?{...item,weight:Number(e.target.value)}:item))} className="h-10 w-16 rounded-xl border border-black/10 text-center text-sm font-bold"/><span className="text-xs">%</span></div></div><input type="range" min={0} max={50} value={w.weight} onChange={(e)=>setWeights((items)=>items.map((item)=>item.id===w.id?{...item,weight:Number(e.target.value)}:item))} className="mt-3 w-full accent-[#0067b1]"/></div>)}</div><div className="mt-8 flex justify-end border-t border-black/[.07] pt-6"><button disabled={total!==100} className="inline-flex h-11 items-center gap-2 rounded-full bg-[#0067b1] px-6 text-xs font-bold text-white disabled:opacity-30"><Icon name="check" className="h-4 w-4"/>Guardar borrador</button></div></section>
<aside className="space-y-5"><section className="rounded-[26px] bg-[#0c1620] p-6 text-white"><div className="text-xs font-bold uppercase tracking-[.14em] text-[#ffd000]">Reglas de salida</div><div className="mt-6 space-y-4">{[["A · 80–100","Asesor de cierre","green"],["B · 65–79","Validación breve","yellow"],["C · 45–64","Nutrición 90 días","blue"],["D · 0–44","Plan de preparación","gray"]].map(([level,route,tone])=><div key={level} className="flex items-center justify-between rounded-[17px] bg-white/[.07] p-4"><div><div className="text-sm font-semibold">{level}</div><div className="mt-1 text-[10px] text-white/45">{route}</div></div><Pill tone={tone as "green"|"yellow"|"blue"|"gray"}>{route}</Pill></div>)}</div></section><section className="surface-card p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#ffd000]/25"><Icon name="shield" className="h-5 w-5"/></span><div><h3 className="text-sm font-semibold">Salvaguardas</h3><ul className="mt-3 space-y-2 text-xs leading-5 text-black/47"><li>No usar variables discriminatorias.</li><li>No presentar score como aprobación.</li><li>No descartar no afiliados automáticamente.</li><li>Registrar razones y versión del modelo.</li><li>Permitir revisión humana y corrección.</li></ul></div></div></section><section className="surface-card p-6"><h3 className="text-sm font-semibold">Métricas de gobierno</h3><div className="mt-4 grid grid-cols-2 gap-3">{[["Completitud","91%"],["Drift","Bajo"],["Explicados","100%"],["90/10","En rango"]].map(([l,v])=><div key={l} className="rounded-[15px] bg-black/[.025] p-4"><div className="text-[9px] text-black/38">{l}</div><div className="mt-1 text-lg font-bold">{v}</div></div>)}</div></section></aside></div>
</PortalShell>}
