export const projects = [
  {
    id: "reserva-del-parque",
    name: "Reserva del Parque",
    city: "Bogotá",
    zone: "Fontibón",
    price: 186000000,
    priceLabel: "$186 M",
    area: "52–68 m²",
    rooms: "2–3",
    delivery: "I semestre 2028",
    compatibility: 94,
    status: "Disponible",
    units: 18,
    image: "/illustrations/project-1.svg",
    features: ["Cerca a TransMilenio", "Zonas verdes", "Salón comunal", "Parque infantil"],
    reason: "Se ajusta a tu presupuesto, ubicación preferida y cuota mensual estimada.",
  },
  {
    id: "senderos-de-la-sabana",
    name: "Senderos de la Sabana",
    city: "Mosquera",
    zone: "Centro",
    price: 164000000,
    priceLabel: "$164 M",
    area: "48–61 m²",
    rooms: "2–3",
    delivery: "II semestre 2027",
    compatibility: 89,
    status: "Últimas unidades",
    units: 7,
    image: "/illustrations/project-2.svg",
    features: ["Cuota inicial flexible", "Zona BBQ", "Cancha múltiple", "Cicloruta"],
    reason: "Su cuota inicial puede cubrirse parcialmente con tus ahorros y cesantías.",
  },
  {
    id: "altos-de-la-floresta",
    name: "Altos de la Floresta",
    city: "Soacha",
    zone: "Ciudad Verde",
    price: 148000000,
    priceLabel: "$148 M",
    area: "45–57 m²",
    rooms: "2",
    delivery: "Entrega inmediata",
    compatibility: 83,
    status: "Disponible",
    units: 32,
    image: "/illustrations/project-3.svg",
    features: ["Entrega inmediata", "Comercio cercano", "Parqueaderos", "Portería 24/7"],
    reason: "Es la alternativa con menor esfuerzo financiero y disponibilidad inmediata.",
  },
];

export const leads = [
  { id: "lead-001", name: "Daniela Rojas", initials: "DR", score: 92, tier: "A", capacity: "$210 M", project: "Reserva del Parque", source: "Meta Ads", date: "21 jul, 10:24", state: "Nuevo", priority: "Alta", phone: "+57 301 555 1842", email: "daniela.rojas@email.com" },
  { id: "lead-002", name: "Miguel Torres", initials: "MT", score: 86, tier: "A", capacity: "$185 M", project: "Senderos de la Sabana", source: "Google Ads", date: "21 jul, 09:48", state: "Cita agendada", priority: "Alta", phone: "+57 315 440 9771", email: "miguel.torres@email.com" },
  { id: "lead-003", name: "Paula Martínez", initials: "PM", score: 74, tier: "B", capacity: "$158 M", project: "Altos de la Floresta", source: "Instagram", date: "20 jul, 18:31", state: "Contactado", priority: "Media", phone: "+57 300 192 7745", email: "paula.m@email.com" },
  { id: "lead-004", name: "Jorge Salazar", initials: "JS", score: 68, tier: "B", capacity: "$172 M", project: "Senderos de la Sabana", source: "Landing orgánica", date: "20 jul, 15:06", state: "En seguimiento", priority: "Media", phone: "+57 312 590 4490", email: "jorge.salazar@email.com" },
  { id: "lead-005", name: "Carolina Méndez", initials: "CM", score: 56, tier: "C", capacity: "$135 M", project: "Sin asignar", source: "TikTok Ads", date: "20 jul, 12:17", state: "Perfil incompleto", priority: "Baja", phone: "+57 310 554 8201", email: "carolina.m@email.com" },
  { id: "lead-006", name: "Andrés Rivera", initials: "AR", score: 81, tier: "A", capacity: "$195 M", project: "Reserva del Parque", source: "Referido", date: "19 jul, 17:54", state: "En negociación", priority: "Alta", phone: "+57 311 481 3884", email: "andres.r@email.com" },
];

export const campaigns = [
  { name: "Vivienda propia Bogotá", channel: "Meta Ads", spend: "$18,4 M", leads: 486, qualified: 172, cpl: "$37.860", cpql: "$106.977", score: 71, conversion: "35,4%", status: "Activa" },
  { name: "Subsidio + vivienda", channel: "Google Ads", spend: "$12,8 M", leads: 294, qualified: 131, cpl: "$43.537", cpql: "$97.710", score: 79, conversion: "44,6%", status: "Activa" },
  { name: "Apartamentos Sabana", channel: "Instagram", spend: "$8,2 M", leads: 315, qualified: 88, cpl: "$26.032", cpql: "$93.181", score: 64, conversion: "27,9%", status: "En revisión" },
  { name: "Entrega inmediata", channel: "TikTok Ads", spend: "$5,6 M", leads: 271, qualified: 49, cpl: "$20.664", cpql: "$114.285", score: 58, conversion: "18,1%", status: "Pausada" },
];
