export const projects = [
  {
    id: "versalles",
    name: "Versalles",
    city: "Soacha",
    zone: "Cundinamarca",
    price: 180000000,
    priceLabel: "$180 M",
    area: "50–62 m²",
    rooms: "2–3",
    delivery: "Por confirmar",
    compatibility: 91,
    status: "Información por validar",
    units: 0,
    image: "/illustrations/project-1.svg",
    features: [
      "Compatible con el presupuesto estimado",
      "Coincide con la ubicación preferida",
      "Adecuado para un hogar de tres personas",
    ],
    reason: "Coincide preliminarmente con la capacidad, ubicación y composición del hogar del escenario Jonathan.",
  },
] as const;

export const leads = [
  {
    id: "lead-jonathan",
    name: "Jonathan",
    initials: "JO",
    score: 82,
    confidence: 0.84,
    capacity: "$145 M",
    project: "Versalles",
    source: "Meta",
    state: "Listo para asesor",
    priority: "Alta",
    phone: "Dato protegido",
    email: "Dato protegido",
    affiliate: "Afiliado verificado",
    route: "Asesor ahora",
    horizon: "4 meses",
    goal: "Comprar vivienda para su familia",
    location: "Soacha",
    blocker: "Validar financiación y beneficios potenciales",
    nextAction: "Agendar una visita y validar financiación",
  },
  {
    id: "lead-laura",
    name: "Laura",
    initials: "LA",
    score: 79,
    confidence: 0.78,
    capacity: "Capacidad alta",
    project: "Por definir",
    source: "Canal propio",
    state: "Ruta no afiliado",
    priority: "Alta",
    phone: "Dato protegido",
    email: "Dato protegido",
    affiliate: "No afiliada",
    route: "Prioridad no afiliado",
    horizon: "Corto plazo",
    goal: "Encontrar una vivienda ajustada a su capacidad",
    location: "Por confirmar",
    blocker: "Gestionar la ruta regulatoria del 10%",
    nextAction: "Validar intención y asignar atención comercial",
  },
  {
    id: "lead-camila",
    name: "Camila",
    initials: "CA",
    score: 48,
    confidence: 0.81,
    capacity: "En preparación",
    project: "Sin asignar",
    source: "Canal propio",
    state: "Nutrición activa",
    priority: "Media",
    phone: "Dato protegido",
    email: "Dato protegido",
    affiliate: "Afiliada",
    route: "Nutrición financiera",
    horizon: "12 meses",
    goal: "Prepararse para comprar más adelante",
    location: "Por confirmar",
    blocker: "Ahorro insuficiente y beneficios por revisar",
    nextAction: "Definir meta de ahorro y revisión en tres meses",
  },
] as const;
