import Link from "next/link";
import { PortalShell } from "@/components/portal-shell";
import { Icon } from "@/components/icon";
import { Pill, StatCard } from "@/components/ui";
import { campaigns } from "@/lib/data";

export default function MarketingDashboardPage(){return <PortalShell role="marketing" title="Calidad del lead, no solo volumen." subtitle="La solución no cambia la pauta: demuestra qué fuentes generan perfiles comparables con el canal orgánico y cuánto cuesta llevarlos al asesor." actions={<Link href="/marketing/campanas" className="inline-flex h-11 items-center gap-2 rounded-full bg-[#0c1620] px-5 text-xs font-semibold text-white">Ver campañas <Icon name="arrow" className="h-4 w-4"/></Link>}>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Leads perfilados" value="1.172" detail="87,3% completó el flujo" icon="users"/><StatCard label="Costo por calificado" value="$101.840" detail="-22% frente al mes anterior" icon="money"/><StatCard label="Afiliados detectados" value="368" detail="Antes de llegar al asesor" icon="shield"/><StatCard label="En nutrición" value="590" detail="No descartados; con próxima acción" icon="clock"/></div>
<div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-black/[.07] p-6"><div><h2 className="text-lg font-semibold">Embudo por fuente</h2><p className="mt-1 text-xs text-black/40">Desde lead captado hasta oportunidad enviada al asesor.</p></div><Pill tone="blue">Referencia: orgánico</Pill></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Campaña</th><th>Leads</th><th>Perfilados</th><th>Afiliados</th><th>Calificados</th><th>CPQL</th></tr></thead><tbody>{campaigns.map((c)=><tr key={c.name}><td><div className="font-semibold">{c.name}</div><div className="mt-1 text-[10px] text-black/40">{c.channel}</div></td><td>{c.leads}</td><td>{c.profiled}</td><td>{c.affiliates}</td><td><b>{c.qualified}</b></td><td>{c.cpql}</td></tr>)}</tbody></table></div></section><section className="rounded-[26px] bg-[#ffd000] p-6"><div className="flex items-center justify-between"><div className="text-xs font-bold uppercase tracking-[.14em]">Insight accionable</div><Icon name="sparkles" className="h-5 w-5"/></div><h2 className="mt-6 text-3xl font-semibold leading-[1] tracking-[-.05em]">Google produce el lead pago más parecido al orgánico.</h2><p className="mt-4 text-xs leading-5 text-black/58">Tiene mayor finalización, proporción de afiliados y conversión a oportunidad A/B. TikTok mantiene volumen, pero requiere nutrición más larga.</p><div className="mt-6 rounded-[20px] bg-white/55 p-4"><div className="flex justify-between text-xs"><span>Brecha vs orgánico</span><b>-6,4 pp</b></div><div className="mt-3 flex justify-between text-xs"><span>Antes del perfilador</span><b>-23,1 pp</b></div></div></section></div>
<div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="surface-card p-6"><h2 className="text-lg font-semibold">Razones para nutrición</h2><div className="mt-6 space-y-5">{[["Cuota inicial insuficiente",34],["Horizonte superior a 6 meses",27],["Capacidad por debajo del inventario",21],["Afiliación por validar",11],["Información incompleta",7]].map(([label,value])=><div key={label as string}><div className="flex justify-between text-xs"><span>{label}</span><b>{value}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-black/[.05]"><div className="h-full rounded-full bg-[#0067b1]" style={{width:`${value}%`}}/></div></div>)}</div></section><section className="surface-card p-6"><h2 className="text-lg font-semibold">Control 90/10</h2><p className="mt-2 text-xs leading-5 text-black/45">Visibilidad temprana del mix de oportunidades con capacidad real, sin confundir lead con venta.</p><div className="mt-7 grid grid-cols-2 gap-4"><div className="rounded-[20px] bg-[#0067b1] p-5 text-white"><div className="text-4xl font-bold">91,6%</div><div className="mt-2 text-xs text-white/60">Oportunidades afiliadas</div></div><div className="rounded-[20px] bg-black/[.035] p-5"><div className="text-4xl font-bold">8,4%</div><div className="mt-2 text-xs text-black/45">No afiliadas priorizadas</div></div></div></section></div>
</PortalShell>}
