import Link from "next/link";
import { PortalShell } from "@/components/portal-shell";
import { Icon } from "@/components/icon";
import { Pill, StatCard } from "@/components/ui";
import { leads } from "@/lib/data";

export default function AsesorDashboardPage(){
  const closing=leads.filter((lead)=>lead.route==="Asesor");
  return <PortalShell role="asesor" title="Bandeja de oportunidades listas." subtitle="Aquí no llegan leads sin explorar: llegan perfiles priorizados con contexto suficiente para validar, agendar y cerrar." actions={<><button className="inline-flex h-11 items-center gap-2 rounded-full border border-black/[.08] bg-white px-5 text-xs font-semibold"><Icon name="download" className="h-4 w-4" />Exportar ficha</button><Link href="/asesor/leads" className="inline-flex h-11 items-center gap-2 rounded-full bg-[#0c1620] px-5 text-xs font-semibold text-white">Abrir bandeja <Icon name="arrow" className="h-4 w-4" /></Link></>}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Listos para cierre" value="7" detail="Score A y afiliación validable" icon="target"/><StatCard label="Tiempo ahorrado" value="31 h" detail="Exploración evitada esta semana" icon="clock"/><StatCard label="Citas de hoy" value="5" detail="Todas con proyecto recomendado" icon="calendar"/><StatCard label="Conversión a visita" value="42,8%" detail="+11,2 pp vs lead sin perfilar" icon="chart"/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
      <section className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-black/[.07] p-6"><div><h2 className="text-lg font-semibold">Prioridad de cierre</h2><p className="mt-1 text-xs text-black/40">Ordenada por score, afiliación, horizonte y afinidad con inventario.</p></div><Pill tone="green">SLA 15 min</Pill></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Lead</th><th>Afiliación</th><th>Score</th><th>Proyecto</th><th>Acción</th></tr></thead><tbody>{closing.map((lead)=><tr key={lead.id}><td><Link href={`/asesor/leads/${lead.id}`} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#0067b1]/10 text-xs font-bold text-[#0067b1]">{lead.initials}</span><div><div className="font-semibold">{lead.name}</div><div className="mt-0.5 text-[10px] text-black/40">{lead.source} · {lead.horizon}</div></div></Link></td><td><Pill tone="blue">{lead.affiliate}</Pill></td><td><b>{lead.score}</b></td><td>{lead.project}</td><td><Link href={`/asesor/leads/${lead.id}`} className="text-xs font-bold text-[#0067b1]">Validar y agendar</Link></td></tr>)}</tbody></table></div></section>
      <div className="space-y-5"><section className="rounded-[26px] bg-[#0067b1] p-6 text-white"><div className="flex items-center justify-between"><div className="text-xs font-semibold text-[#ffd000]">Siguiente mejor acción</div><Icon name="sparkles" className="h-5 w-5"/></div><h3 className="mt-5 text-2xl font-semibold tracking-[-.04em]">Contacta primero a Daniela Rojas.</h3><p className="mt-3 text-xs leading-6 text-white/65">Afiliada, score 94, compra en menos de 3 meses y 94% de afinidad con Reserva del Parque.</p><button className="mt-5 inline-flex h-10 items-center gap-2 rounded-full bg-white px-4 text-xs font-bold text-[#0067b1]"><Icon name="phone" className="h-4 w-4"/>Llamar ahora</button></section><section className="surface-card p-6"><h2 className="text-lg font-semibold">Lo que ya sabemos</h2><div className="mt-5 space-y-3">{[["Afiliación","Validable"],["Capacidad","$175M–$210M"],["Subsidio","Potencial"],["Pendiente","Saldo de cesantías"]].map(([l,v])=><div key={l} className="flex justify-between rounded-[15px] bg-black/[.025] p-3 text-xs"><span className="text-black/45">{l}</span><b>{v}</b></div>)}</div></section></div>
    </div>
  </PortalShell>
}
